### ISSUE TITLE
Rustacean.org not working on Firefox nightly

### ISSUE THREAD

**Issue by enricostano** [nrc/rustaceans.org#221]
Errors in console:
```
DEBUG: -------------------------------ember.js:3285:9
DEBUG: Ember      : 1.3.0ember.js:3285:9
DEBUG: Ember Data : 1.0.0-beta.5ember.js:3285:9
DEBUG: Handlebars : 1.0.0ember.js:3285:9
DEBUG: jQuery     : 1.10.2ember.js:3285:9
DEBUG: -------------------------------ember.js:3285:9
NS_ERROR_FAILURE: 
Ember.HistoryLocation<.replaceState()
ember.js:37591
Ember.HistoryLocation<.initState()
ember.js:37484
Ember.Router<._setupLocation()
ember.js:33740
Ember.Router<.init()
ember.js:33561
superWrapper()
ember.js:1230
makeCtor/Class()
ember.js:12325
ClassMixin<.create()
```
Firefox details:
Firefox Developer Edition 48.0a2 (2016-04-29)

Working OK on Chrome

**Comment by nrc** [comment]
Did you have to do anything for this to happen, or was it just on loading the page?

**Comment by enricostano** [comment]
LOL it's working today... same version. But yes, just loading the page with almost 0 plugins/extensions.

Feel free to close if cannot reproduce.

**Comment by nrc** [comment]
I couldn't repro, so closing for now. I've been having a few server problems, so it might be related to that some how. Please feel free to re-open if it happens again.
