### ISSUE TITLE
I don't exist?

### ISSUE THREAD

**Issue by Aaronepower** [nrc/rustaceans.org#289]
despite `Aaronepower.json` existing in the repo, I do not show up in rustaceans, either through search or by [direct URL](http://rustaceans.org/Aaronepower)

**Comment by nrc** [comment]
I've tried looking in to this - we used to have a bug where a random person would be missed every now and again, but you're still missing after a few reboots and I can't work out why. Will need some more investigation, sorry!

**Comment by sriram23** [comment]
Me too have same issue

**Comment by nrc** [comment]
Fixed, sorry it took so long
