### ISSUE TITLE
Profile merged but no URL created!

### ISSUE THREAD

**Issue by AsmaSwapna** [nrc/rustaceans.org#365]
My profile update is recently merged but I don't exist in the site yet and neither any URL is created to the profile.
Any comments on that? @nrc

**Comment by nrc** [comment]
Hey, sorry been meaning to look into this. There seems to be nothing wrong with the data, but the site is indeed missing your details. Will report back...

**Comment by nrc** [comment]
Hey, this is fixed now - http://www.rustaceans.org/AsmaSwapna

**Comment by AsmaSwapna** [comment]
Hey thanks!
