### ISSUE TITLE
expired SSL certificate on rustaceans.org

### ISSUE THREAD

**Issue by 5ubbu** [nrc/rustaceans.org#645]
The SSL certificate seems to have expired on https://rustaceans.org/ - I landed on this page from rustacean.net and chanced across this.

**Comment by nrc** [comment]
Thanks! It's on my todo list, but is blocked on a server-migration at the moment. Should be fixed in the next week or so.

**Comment by nrc** [comment]
This should now be fixed. Please let me know if there are any problems
